### ISSUE TITLE
Should keys describe what they are used for?

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/did-spec#10]
There are three approaches that we could use for what keys can be used for in the DID specification:

1. Annotate keys so that you know whether they can be used for signing, encryption, authentication, etc.
2. Associate keys with capabilities instead of annotating those capabilities directly on the key.
3. A hybrid of 1 and 2, which is more complicated, but provides more flexibility.

**Comment by talltree** [comment]
I am in favor of DID key descriptions including as much semantic description of the intended uses (or restrictions on) a key as required for that type of key or specific uses of that type of key. But IMHO those semantics should be encapsulated in the key description and not affect anything else in the DDO.

**Comment by msporny** [comment]
> should be encapsulated in the key description and not affect anything else in the DDO.

What about Guardian keys and recovery keys? Don't those affect the DDO (or how it's processed)?

**Comment by msporny** [comment]
@dlongley and I had a quick discussion about this in the office and came up with these two assertions (which may or may not be correct):

1. A DDO MUST list what keys are allowed to do what to the DDO (e.g. Update the DDO).
2. A public key description in a DDO MAY describe limitations for what the key can be used for (e.g. authenticate, or update a DDO).

You fundamentally need 1, and you may need 2 (seems useful). Therefore, we either need to do 1 or 1 and 2. Just doing 2 isn't enough, because your annotations on your keys are meaningless unless the DDOs that list them (like those of refugees) say that the keys are allowed to do certain things to *their* DDOs.

Here's a concrete example:

1. Reena's DDO expresses that her guardian is UNHCR and the key to update her DDO is did:example:UNHCR/key-1.
2. The UNHCR DDO expresses did:example:UNHCR/key-1 and annotates it with the `UPDATE_DDO` annotation so that people know that it can be used to update a DDO. Other annotations for other keys may be `AUTHENTICATE` or `DIGITALLY_SIGN_EMAIL` or something else.

I suggest we use the example above to iterate through the various options.

**Comment by msporny** [comment]
> I don't think that keys have agency. They are an authentication mechanism. Entities have agency -- and you identify them, typically, via DIDs [in the DDO]. I think we need to be careful with this distinction our modeling.

yes, +1, I think this is the heart of the issue.

/cc @rxgrant @ChristopherA @kimdhamilton

**Comment by msporny** [comment]
The group has resolved this issue by:

1. Specifying the usage characteristic of the cryptographic material (e.g. key) is expressed via the `type` field. For example: `RsaSigningKey2018`.
2. Ensuring that the algorithm for finding a key in order to perform verification of a cryptographic proof (e.g. digital signature) travels through an application/purpose field (e.g. `authentication`), which is associated with a cryptographic suite (e.g. `RsaSignatureAuthentication2018`).

This provides a broad definition of what cryptographic material (e.g. key) can be used for (e.g. signing) and an application purpose (e.g. authenticating). Closing the issue as the groups thinking on this seems to be pretty solid these days.
