### ISSUE TITLE
Decentralized Identifiers (DIDs)  for Devices (DIDDs): Extending, Harmonizing, Leveraging and Incorporating DID spec to GS1 Standards / Unique Device Identification (UDI)

### ISSUE THREAD

**Issue by nathanawmk** [w3c-ccg/did-spec#100]
I wish to extend DIDs to devices and machines, therefore I would like to propose Decentralized Identifiers (DIDs)  for Devices (DIDDs).

As is today, devices are already unique due to some available standards out there. 

Thus, one could extend, Harmonize, Leverage and Incorporate DID spec to GS1 Standards / Unique Device Identification (UDI)

Existing GS1 standards / UDIs can also further leverage DID specs to enable a decentralized supply chain tracking system and vice versa as GS1 standards/UDIs 

How can one contribute to Decentralized Identifiers (DIDs)  for Devices (DIDDs)?

Thank you. 

References:
https://www.gs1.org/healthcare/udi

**Comment by msporny** [comment]
Hi @nathanawmk, thanks for raising this issue. At present, there are already a number of projects that are using DIDs for devices. So, no further extension is necessary to the spec as far as we can tell (the current spec works just fine for IoT devices and IoT swarm controllers that handle key material on behalf of the devices and/or relay information for the IoT devices).

We've also been working w/ a few folks at GS1, not specifically on IoT, but with respect to Verifiable Credentials and DIDs (GTIN stuff, mostly). So, there is high level alignment on re-using GS1 identifiers in this ecosystem.

There are a variety of ways you could contribute. The best way is to join the [W3C Credentials Community Group](https://w3c-ccg.github.io/), which is in charge of pushing the DID spec forward at W3C.  There is also the [W3C Verifiable Claims Working Group](https://www.w3.org/2017/vc/WG/), which is working on expressing digitally signed credentials.

**Comment by nathanawmk** [comment]
Sure.

**Comment by rhiaro** [comment]
Closing as I think this conversation is over, but please re-open if there are more questions on this topic.
