### ISSUE TITLE
Definition of a valid value property of a public key is vague.

### ISSUE THREAD

**Issue by gjgd** [w3c-ccg/did-spec#105]
According to the examples given [here](https://github.com/w3c-ccg/did-spec/blob/4b0d5e9a905f1bc34bb1381829701a9c45960b18/index.html#L1154-L1157), it is not clear if the format of the value property for a public key should be `publicKey<ENCODING>` or if it can be anything (eg `ethereumAddress` like in the [Uport's repo](https://github.com/uport-project/ethr-did) )

**Comment by aljones15** [comment]
I agree with this one and I think the current spec is even more confusing:

> The value of the publicKey property MUST be an array of public keys, and every public key property MUST be in the Linked Data Cryptographic Suite Registry.

I believe value property refers to one of:

> The following is a non-exhaustive list of public key properties used by the community: publicKeyPem, publicKeyJwk, publicKeyHex, publicKeyBase64, publicKeyBase58, publicKeyMultibase, ethereumAddress.

I think it would be clearer if reworded:

Each public key MUST include id and type properties, and exactly one value property as defined in [Linked Data Cryptography Suites and Key Formats.](https://w3c-ccg.github.io/ld-cryptosuite-registry/). The array of public keys SHOULD NOT contain duplicate entries with the same id and different value properties with different formats.

**Comment by dlongley** [comment]
> "and exactly one value property"

We should not have a requirement that a public key can't list its material in more than one format. The material should not be different, but there may be some client software that only understands `publicKeyPem` and other client software that only understands `publicKeyBase58` ... and you should be able to list both in your public key to allow for interop with both.

**Comment by peacekeeper** [comment]
I believe this has been addressed by https://github.com/w3c-ccg/did-spec/pull/202 and can be closed.
