### ISSUE TITLE
Introduction incorrectly states requirements for DID documents

### ISSUE THREAD

**Issue by dlongley** [w3c-ccg/did-spec#112]
The introduction states

> Each DID Document contains at least three
things: cryptographic material, authentication suites, and service
endpoints.

https://github.com/w3c-ccg/did-spec/blob/gh-pages/index.html#L142-L144

But none of these things are actually *requirements* for DID documents per the rest of the spec (which I believe to be correct). A DID Document only *must* have an `@context` and an identifier, nothing more is strictly required. This is in keeping with the spirit that a DID Document describe anything at all; it needn't be restricted to descriptions of entities that control cryptographic material, can authenticate, and have services, etc. -- despite those representing perhaps the most common use case.

**Comment by msporny** [comment]
This has been addressed by a PR that has been merged.
