### ISSUE TITLE
[Abstract] The term "DID subject" is used extensively throughout this key paragraph without being defined/introduced

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#115]
In the Abstract, the term "DID subject" is used extensively throughout this key paragraph without being defined/introduced.  For example,

> Decentralized Identifiers (DIDs) are a new type of identifier for verifiable, "self-sovereign" digital identity. DIDs are fully under the control of the DID subject, independent from any centralized registry, identity provider, or certificate authority. DIDs are URLs that relate a DID subject to means for trustable interactions with that subject. DIDs resolve to DID Documents — simple documents that describe how to use that specific DID.

Later on section https://w3c-ccg.github.io/did-spec/#did-subject, DID subject is defined as:

> The DID subject is the identifier that the DID Document is about, i.e., it is the DID described by DID Document.
 
1. The Abstract needs to be updated to introduce DID subject [or not reference the term at all].
2. [CRITICAL] When the concept of DID subject defined in 4.2 is combined with the Abstract, things become circular from a definitional perspective ...as well as from the perspective of someone reading the draft specification for the first time ...it's [#confuding](https://hyperonomy.com/2018/12/18/definition-confuding/) for new developers.

The definition of *what* a DID is needs to be clear and precise.  It needs to be made more clear and precise in the first sentence or two of the Abstract.

Cross referenced with issue: https://github.com/w3c-ccg/did-spec/issues/139

NOTE: If section https://w3c-ccg.github.io/did-spec/#did-subject is deleted, Example 4 needs to be moved elsewhere in the draft DID spec as it is the only representation of the "world's simplest" DID document (which needs to be kept in the spec).

**Comment by TomCJones** [comment]
the only solution to the definition problem raised here is to avoid use of technical terms in the abstract. To follow the recommendation of @mwherman2000  is to put the entire contents of the spec into the abstract, which is not the intent of an abstract.

**Comment by mwherman2000** [comment]
The most critical issue is that the definition (point 2 in the original issue) is circular.  The more general feedback in this section and throughout the document, as a specification, it needs to be more accurate and precise ...it's a theme of many of the issues I've posted in the last couple weeks.  The Abstract is the first example of the problem.

**Comment by TomCJones** [comment]
Decentralized Identifiers (DIDs) are a new type of identifier for verifiable, "self-sovereign" digital identity. DIDs are controlled by a subject using a method which can be fully decentralized. DIDs are URLs that point to DID Documents — simple documents that describe how to use that specific DID under the rules given by the method used to create the DID. DIDs are of the form DID:{method}:{identifier}.

**Comment by TomCJones** [comment]
actually - come to think of it - DIDs point to a means to render a DID document, which may not actually exist until it is requested.

**Comment by mwherman2000** [comment]
> actually - come to think of it - DIDs point to a means to render a DID document, which may not actually exist until it is requested.

Tom, I've included (what I believe) is a workable definition of a DID here (updated today): 
[Decentralized Identifiers (DIDs) Architecture Reference Model (ARM)](https://hyperonomy.com/2018/12/21/decentralized-identifiers-dids-architecture-reference-model-arm/).

I think it's actually better than `workable`, it's precise and accurate.

Scroll down the page to the heading **Version 0.11 – December 30, 2018** and start reading from there.  If you need/want more background, start reading from the top.

**Comment by mwherman2000** [comment]
Isn't Subject a "higher level concept" (e.g. from Verified Credentials) that has somehow crept down into these lower level concepts of DID Documents, DID Entities, etc?

For the Abstract, I think the entire discussion of "DID subject" is not that useful and can be removed.

**Comment by jandrieu** [comment]
Closing as we have adopted this issue in the new DIDWG repo, where we are seeking consensus on the terms for Subject, Controller, and authenticatee/authenticating parties.
