### ISSUE TITLE
[Overview] "Because DIDs reside on a distributed ledger" - not true?

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#119]
In https://w3c-ccg.github.io/did-spec/#overview, it states....

> This design eliminates dependence on centralized registries for identifiers as well as centralized certificate authorities for key management—the standard pattern in hierarchical PKI (public key infrastructure). Because DIDs reside on a distributed ledger, each entity may serve as its own root authority—an architecture referred to as DPKI (decentralized PKI).

1. "Because DIDs reside on a distributed ledger" What is a DID?  If a DID is a character string identifier, then it doesn't live on the the ledger, the DID Document lives on the ledger.  See the following diagram...

[Hyperledger Indy/Sovrin Comprehensive Architecture Reference Model (INDY ARM) - latest version](https://hyperonomy.com/2019/01/13/hyperledger-indy-sovrin-comprehensive-architecture-reference-model-arm/) - bullets (12) thru (16) in both the diagram, Narration, and principles.

Reword/clarify (here and throughout the draft specification).

**Comment by jandrieu** [comment]
Closing as we have moved this over to the DIDWG did-spec repo.
