### ISSUE TITLE
[Motivations for DIDs]: "The new type of URL SHOULD NOT require a centralized authority to...

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#120]
In https://w3c-ccg.github.io/did-spec/#motivations-for-dids, it states...

> The new type of URL SHOULD NOT require a centralized authority to register, resolve, update, or revoke the identifier. The overwhelming majority of URIs today are based on DNS names or IP addresses that depend on centralized authorities for registration and ultimate control. DIDs can be created and managed without any such authority.

While I understand the philosophy, in a real world scenario, a software agent (aka DID Resolver) IS REQUIRED for a DID-based platform to function, n'est pas? 

I think this requirement needs to be either struck/removed or reworded in some way?

Reference: [Hyperledger Indy/Sovrin Comprehensive Architecture Reference Model (INDY ARM) - latest version](https://hyperonomy.com/2019/01/13/hyperledger-indy-sovrin-comprehensive-architecture-reference-model-arm/) - bullets (12) thru (16) in both the diagram, Narration, and principles.

**Comment by rhiaro** [comment]
A DID resolver is not a centralized authority, it's a library or a service anybody can run. So I don't think there's anything to address here.
