### ISSUE TITLE
[Motivation for DIDs] should read "how to register, resolve, update, or revoke a DID Entity/DID Document (the latter being the JSON-LD serialization of the former)"

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#122]
In https://w3c-ccg.github.io/did-spec/#motivations-for-dids, it states...

> to register, resolve, update, or revoke the identifier.

(...in the larger context of...

> The new type of URL SHOULD NOT require a centralized authority to register, resolve, update, or revoke the identifier._

This is a great example of where the term identifier (aka DID, the character string identifier) is being overloaded creating a huge amount of [#confudsion](https://hyperonomy.com/2018/12/18/definition-confuding/) with first time readers and any reviewer trying to validate this draft specification for completeness, accuracy and precision.

This _part_ of the spec/protocol document (also see https://github.com/w3c-ccg/did-spec/issues/121) is/should be about _how to register, resolve, update, or revoke a DID Entity/DID Document (the latter being the JSON-LD serialization of the former)_ ...and not about how to register, resolve, update, or revoke the identifier.

This and several other similar references need to be corrected.  Please don't overload the term "DID", the character string identifier.

Reference: [Hyperledger Indy/Sovrin Comprehensive Architecture Reference Model (INDY ARM) - latest version](https://hyperonomy.com/2019/01/13/hyperledger-indy-sovrin-comprehensive-architecture-reference-model-arm/) - bullets (12) thru (16) in both the diagram, Narration, and principles.

**Comment by jandrieu** [comment]
Closing as this phrase is no longer in the DID spec. Please feel free to raise a new issue if the general problem you are concerned about is still present in the current draft at https://w3c.github.io/did-spec/
