### ISSUE TITLE
[Design Goals] all references to *identifier* management etc. should be changed to *DID Entity* management, etc.

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#123]
In https://w3c-ccg.github.io/did-spec/#design-goals, it refers to

> identifier management, including the registration of globally unique identifiers, public verification keys, service endpoints, and other metadata.

This isn't about *identifier management* at all.  It's about the management of DID Entities.

Reference: [Hyperledger Indy/Sovrin Comprehensive Architecture Reference Model (INDY ARM) - latest version](https://hyperonomy.com/2019/01/13/hyperledger-indy-sovrin-comprehensive-architecture-reference-model-arm/) - bullets (12) thru (16) in both the diagram, Narration, and principles.

**Comment by rhiaro** [comment]
There's no formal concept of a "DID Entity" and commits https://github.com/w3c-ccg/did-spec/commit/776406cf4e4658a622308489775293be1db14556 https://github.com/w3c-ccg/did-spec/commit/418ab1b38c6d35b9a7544da75de9799630780830 https://github.com/w3c-ccg/did-spec/commit/12e0a18a277e939458736ad39eba7a26f51e6070 https://github.com/w3c-ccg/did-spec/commit/4a248495b4f983bb67ddddad925a61c6615a1b10 around ambiguous "entity" terminology should hopefully clear this up and mean this issue can be closed.

**Comment by mwherman2000** [comment]
In the proposed changes, I don't see where the specific term "identifier management" was changed or removed.  Please leave this issue open.

Also note: https://github.com/w3c-ccg/did-spec/issues/140#issuecomment-469043668

**Comment by peacekeeper** [comment]
> This isn't about _identifier management_ at all.

@mwherman2000 I don't understand. The DID spec defines identifiers and CRUD operations to manage them. So why is this particular design goal (Decentralization) not about _identifier management_?

**Comment by jandrieu** [comment]
Closing as this has been moved to the DIDWG repo.
