### ISSUE TITLE
[TERMOINOLOGY] "Decentralized Identity Management" should be changed to "Decentralized Entity Management"

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#124]
in https://w3c-ccg.github.io/did-spec/#terminology, it states...

>>Decentralized Identity Management
>>Identity Management based on decentralized identifiers. Decentralized Identity Management extends the identifier creation authority beyond the traditional roots of trust required by X.500 directory services, the Domain Name System, and most national ID systems.

This specification is not about the management of decentralized identifier character strings.  

It's about DID Entity Management where DID Entities (and DID Documents, the JSON-LD serialization of a DID Entity)) are the items being managed.

Related to https://github.com/w3c-ccg/did-spec/issues/123.

Reference: [Hyperledger Indy/Sovrin Comprehensive Architecture Reference Model (INDY ARM) - latest version](https://hyperonomy.com/2019/01/13/hyperledger-indy-sovrin-comprehensive-architecture-reference-model-arm/) - bullets (12) thru (16) in both the diagram, Narration, and principles.

**Comment by mwherman2000** [comment]
DID Entities (and DID Documents, the JSON-LD serialization of a DID Entity) contain a DID as an attribute which in turn is used to index a collection of DID Entities/DID Documents ...stored on the Ledger or elsewhere.

**Comment by rhiaro** [comment]
I don't think we need to change this generic definition of "Decentralized Identity Management", plus various commits (https://github.com/w3c-ccg/did-spec/commit/776406cf4e4658a622308489775293be1db14556 https://github.com/w3c-ccg/did-spec/commit/418ab1b38c6d35b9a7544da75de9799630780830 https://github.com/w3c-ccg/did-spec/commit/12e0a18a277e939458736ad39eba7a26f51e6070 https://github.com/w3c-ccg/did-spec/commit/4a248495b4f983bb67ddddad925a61c6615a1b10) around "entity" terminology should hopefully clear this up and mean this issue can be closed.

**Comment by mwherman2000** [comment]
@rhiaro  https://github.com/w3c-ccg/did-spec/commit/4a248495b4f983bb67ddddad925a61c6615a1b10 highlights an ambiguous reference to a "DID".  This reference to a DID needs to be further qualified.  E.g. change "DID" to "DID Document".

> An entity who creates a DID for a <a>dependent</a> who
does not yet have the capacity to control the private keys.

**Comment by rhiaro** [comment]
Thanks Michael, updated in https://github.com/w3c-ccg/did-spec/commit/1d4926ac775aed3f94ed407c4284efc3a42aba4c
