### ISSUE TITLE
[TERMINOLOGY] DID Fragment issues

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#126]
In https://w3c-ccg.github.io/did-spec/#terminology, it states...

>>DID Fragment
>>The portion of a DID reference that follows the first hash sign character ("#"). A DID fragment uses the same syntax as a URI fragment. See section 5.5. Note that a DID fragment MUST immediately follow a DID. If a DID reference includes a DID path followed by a fragment, that fragment is NOT a DID fragment.

1. RE: "Note that a DID fragment MUST immediately follow a DID."  Not true.  
The first hash sign character ("#"), if present, must immediately follow the the DID.  The DID Fragment, if present, must immediately follow the first hash sign character ("#").

**Comment by dmitrizagidulin** [comment]
Addressed in #168.

**Comment by peacekeeper** [comment]
I think this has been fixed by #189. Closing.
