### ISSUE TITLE
[TERMINOLOGY] The definition of a DID Reference omits the need for the punctuation character

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#128]
In https://w3c-ccg.github.io/did-spec/#terminology, it states...

>DID Reference
>A DID plus an optional DID path or DID fragment.

This definition omits the first hash sign character ("#") for DID Fragements, and first forward slash character in the case of DID Paths. 

The current definition is incomplete and confuding.

**Comment by dmitrizagidulin** [comment]
Addressed in PR #168.
