### ISSUE TITLE
[TERMINOLOGY] The definition (the specific wording) of/for DID Scheme is confuding.

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#129]
In https://w3c-ccg.github.io/did-spec/#terminology, it states...

>DID Scheme
>The formal syntax of a Decentralized Identifier. The generic DID scheme is defined in this specification. A DID method specification defines a specific DID scheme that works with a specific DID method.

1. The definition (the specific wording) of/for DID Scheme is confuding.

**Comment by dmitrizagidulin** [comment]
Addressed in PR #168 (or actually, I think even an earlier PR).
