### ISSUE TITLE
[TITLE] Is the title of this draft specification correct/precise?

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#130]
The current title of the current draft specification is:

>Decentralized Identifiers (DIDs) v0.11
>Data Model and Syntaxes for Decentralized Identifiers (DIDs)

I'm serious about questioning the title.  Is the purpose of this draft document to be...

- a specification for Decentralized Identities? ...or... 
- a specification for Decentralized Identifiers? ...or...
- a specification about the more general concept of Trusted Decentralized Entities or Trusted Decentralized Resources?

Context: I am investigating the use of the Indy software platform and Sovrin governance framework for representing and managing Non-Fungible Entities, in general, and OASIS UBL Business Documents, in particular.

**Comment by mwherman2000** [comment]
...or after reviewing the draft DID spec and developing the INDY ARM, should the title of this spec actually be about Decentralized Entities ...or DID Entries.  The significance of a _id (DID)_ (aka a "DID") is over emphasized.  I don't believe the _id (DID)_ is that this specification is about/should be about.

Misuse of "DID" ...see https://github.com/w3c-ccg/did-spec/issues/121#issuecomment-455267182

Reference: [Hyperledger Indy/Sovrin Comprehensive Architecture Reference Model (INDY ARM) - latest version](https://hyperonomy.com/2019/01/13/hyperledger-indy-sovrin-comprehensive-architecture-reference-model-arm/) - bullets (12) thru (16) in both the diagram, Narration, and principles.

**Comment by rhiaro** [comment]
I think the spec text and structure has been sufficiently clarified now that identifiers and the data model are clearly the subject of the spec, so the title and subtitle are correct.

**Comment by mwherman2000** [comment]
Please change

> Decentralized Identifiers (DIDs) v0.11
> Data Model and Syntaxes for Decentralized Identifiers (DIDs)

to 

Decentralized Identifiers (DIDs) v0.11
Core Data Model and Syntaxes for Decentralized Identifiers (DIDs)

to be consistent with the use of Core Data Model.

Reference: https://github.com/w3c-ccg/did-spec/issues/151#issuecomment-469041078
