### ISSUE TITLE
[The Generic DID Scheme] References are not referred to consistently e.g. "[RFC3986]" .vs "[URI]"

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#132]
In https://w3c-ccg.github.io/did-spec/#the-generic-did-scheme, it states

> The generic DID scheme is a URI scheme conformant with [RFC3986].

...but the reference [RFC3986] doesn't appear in section https://w3c-ccg.github.io/did-spec/#normative-references - rather it appears as [URI] and needs to be corrected in one place or the other...

> [URI]
> Uniform Resource Identifier (URI): Generic Syntax. T. Berners-Lee; R. Fielding; L. Masinter. IETF. January 2005. Internet Standard. URL: https://tools.ietf.org/html/rfc3986

**Comment by mwherman2000** [comment]
The problem also exists in https://w3c-ccg.github.io/did-spec/#fragments

**Comment by mwherman2000** [comment]
The problem also exists in https://w3c-ccg.github.io/did-spec/#paths

**Comment by mwherman2000** [comment]
An example where the references in the body of the spec really need to reference the actual RFC by number is **https://w3c-ccg.github.io/did-spec/#bib-urn** ...this entry in https://w3c-ccg.github.io/did-spec/#normative-references RFC 2141 which is obsolete.  This particular scenario (URN) needs to be changed to https://tools.ietf.org/html/rfc8141  CC: @msporny

**Comment by mwherman2000** [comment]
TODO: All of the references in https://w3c-ccg.github.io/did-spec/#normative-references need to be reviewed for obsolete RFC references.

**Comment by rhiaro** [comment]
I updated the URI and URN references as suggested by @mwherman2000 and reviewed all the other normative references for obsolete ones, finding none.
