### ISSUE TITLE
[Specific DID Method Schemes] Reference to "The fully qualified DID" ...not necessary

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#134]
In https://w3c-ccg.github.io/did-spec/#specific-did-method-schemes, it states...

>The fully qualified DID as defined by the DID rule in Section 3.1 The Generic DID Scheme MUST be globally unique.

1. What is a "fully qualified DID"? ...this term/phrase is not used any place else in the draft specification.
2. Can "fully qualified" be removed?
3. What is a "not-full qualified DID"?

**Comment by dmitrizagidulin** [comment]
Addressed in PR #168. (Removed mentions of 'fully qualified').
