### ISSUE TITLE
[Specific DID Method Schemes] Names of "ABNF rules" not named consistently (capitalization)

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#135]
In https://w3c-ccg.github.io/did-spec/#specific-did-method-schemes, it states...

> The fully qualified DID as defined by the DID rule in

In https://w3c-ccg.github.io/did-spec/#the-generic-did-scheme, it states...

> conforming to the did rule in 

as well as

> did                = "did:" method ":" specific-idstring

1. Is the lower-case naming pattern correct?
2. Should the occurrences of upper case rule names be changed to lower case rule names?  e.g. DID rule > did rule

**Comment by dmitrizagidulin** [comment]
Fixed in PR #168.
