### ISSUE TITLE
[The Generic DID Scheme] ABNF definitions for did-path and did-fragment are missing from the draft specification

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#136]
In https://w3c-ccg.github.io/did-spec/#the-generic-did-scheme, it states...

> Following is the ABNF definition using the syntax in [RFC5234] (which defines ALPHA as upper or lowercase A-Z).
> did-reference      = did [ "/" did-path ] [ "#" did-fragment ]
> did                = "did:" method ":" specific-idstring
> method             = 1*methodchar
> methodchar         = %x61-7A / DIGIT
> specific-idstring  = idstring *( ":" idstring )
> idstring           = 1*idchar
> idchar             = ALPHA / DIGIT / "." / "-"
> See Sections 3.3 Paths and 3.4 Fragments for the ABNF rules defining DID paths and fragments.

1. No did-path rule is defined in this section
2. No did-fragment rule is defined in this section
3. No did-path rule is defined anywhere in the draft specification (e.g. https://w3c-ccg.github.io/did-spec/#paths does not contain an ABNF rule for did-path)
4. No did-fragment rule is defined anywhere in the draft specification (e.g. https://w3c-ccg.github.io/did-spec/#fragments does not contain an ABNF rule for did-fragment)

**Comment by dmitrizagidulin** [comment]
Addressed in PR #168 -- the ABNF rules for query, path and fragment components are defined in the URI RFC; they are intentionally not re-specified here.
