### ISSUE TITLE
[Public Keys] re: referenced keys: Is multiple level recursion allowed?

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#143]
In https://w3c-ccg.github.io/did-spec/#public-keys, it states...

> A key may be embedded or referenced in a DID Document. For example, the authentication property may refer to keys in both ways:

Is multiple level recursion allowed for referenced keys? ...if not, it the level limited to 1?

The draft specification needs to be explicit/more clear/transparent about this.

**Comment by mwherman2000** [comment]
It's important to read and understand this section to understand what this issue is referring to.

**Comment by peacekeeper** [comment]
@mwherman2000 while an `authentication` property can reference a public key, the public key can not reference another public key. So I don't see how any kind of recursion or loop would be possible?

Can you give an example?

**Comment by jandrieu** [comment]
Closing as this has been moved to the DIDWG repo.
