### ISSUE TITLE
[Authentication] First sentence is confusing

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#145]
In https://w3c-ccg.github.io/did-spec/#authentication, it states

> Authentication is the mechanism by which an entity can cryptographically prove that they are associated with a DID and DID [Document].

1. Use of entity is vague.  What does it refer to? ...be specific/more precise
2. Is this sentence only true for Actors? ...what about Things?  What needs to be fixed for it to address both Actors and Things?
3. Use of "entity" is confuding.  See  https://github.com/w3c-ccg/did-spec/issues/117

Reference: [Hyperledger Indy/Sovrin Comprehensive Architecture Reference Model (INDY ARM) - latest version](https://hyperonomy.com/2019/01/13/hyperledger-indy-sovrin-comprehensive-architecture-reference-model-arm/) - bullets (12) thru (16) in both the diagram, Narration, and principles.

**Comment by mwherman2000** [comment]
Similarly, with this phrase a little further down: Does it only apply to Actors? ...how does the following phrase need to be reworded to apply to both Actors and Things?

> without enabling them to prove ownership (and thus be able to impersonate the entity).

**Comment by rhiaro** [comment]
Use of "entity" fixed in https://github.com/w3c-ccg/did-spec/commit/12e0a18a277e939458736ad39eba7a26f51e6070
