### ISSUE TITLE
[DID Operations] "all the operations required of a CKMS" are not specified on the body of this section

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#147]
In https://w3c-ccg.github.io/did-spec/#did-operations, it states...

> Note that, due to the specified contents of DID Documents, these operations can effectively be used to perform all the operations required of a CKMS (cryptographic key management system), e.g.:
> - Key registration
> - Key replacement
> - Key rotation
> - Key recovery
> - Key expiration

1. None of these requirements are elaborated on in this section.  Only Create, Read/Verify, Update, and Delete/Revoke are listed.  Where are the CKMS requirements elaborated on?

2. Should "specified" be changed to "specific"?

**Comment by jandrieu** [comment]
Closing as this has been moved to the DIDWG repo.
