### ISSUE TITLE
[Authorization and Delegation] Is this sentence correct if there is no requirement to use a Ledger?

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#149]
In https://w3c-ccg.github.io/did-spec/#authorization-and-delegation, it states...

> Since Authorization and Delegation are typically implemented by the ledger, each DID Method specification is expected to detail how authorization and delegation are performed for the ledger.

In https://w3c-ccg.github.io/did-spec/#terminology, it states...

> A globally unique identifier that does not require a centralized registration authority because it is registered with distributed ledger technology or other form of decentralized network

The implication of the second quoted sentence is that a distributed ledger (aka ledger) technology is not required to implement a system that conforms with this draft DID spec.  If so, why is ledger used in the first quoted sentence?

**Comment by OR13** [comment]
Agree, an alternative:

Each DID Method _MUST_ define how authorization and delegation are implemented, including any necessary cryptographic operations.
 
The sentence could also simply removed.
