### ISSUE TITLE
"distributed ledger" and "ledger" used randomly (in place of one-and-other)

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#150]
Throughout the document, both "distributed ledger" and "ledger" are used randomly (in place of one-and-other).

Strong suggestion: On first use, "distributed ledger" should appear as "distributed ledger (ledger)".  All subsequent references should consistently refer to "ledger" ...only ...as a single word.

**Comment by mwherman2000** [comment]
Side bar: Should (all forms) of "ledger" be changed to "journal"? ...serious request (that is not likely to be adopted).   Reference: https://www.linkedin.com/feed/update/urn:li:activity:6487812287863283712

In discussions about the future directions for the Indy Wallet, we've talked about the introduction of the `subledgers` (https://www.cliffsnotes.com/study-guides/accounting/accounting-principles-i/subsidiary-ledgers-and-special-journals/subsidiary-ledgers) ...which is potentially confuding with the way "ledger" is currently used in the Indy project.

In the real world, what we're calling a "ledger" in the Indy (and most blockchain) projects is actually a journal.  Referernce: https://keydifferences.com/difference-between-journal-and-ledger.html#ComparisonChart

**Comment by jandrieu** [comment]
Interesting suggestion. I expect the use of ledger lacks the kinds of rigor we should aim for. However I'm not sure "journal" is better.

What we really mean is the decentralized data store of record. Or something like that. I hesitate to dive into bike shedding, but certainly "ledger" of any kind is a disservice to DIDs that don't use DLTs, and instead use other storage mechanisms like IPFS or the hypothetical "data" method (similar to the data scheme URLs).
