### ISSUE TITLE
[Design Goals] Vague references to "entities" need to be clarified

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#154]
In https://w3c-ccg.github.io/did-spec/#design-goals, it refers to "entities" in several places ...but in a vague way.

From https://github.com/w3c-ccg/did-spec/issues/116, What does "entities" refer to? This is vague. What are these "entities" in real-life? ...in a DID data model, what/where are these "entities"? For example, do we need to specifically identify/call out the concept of a DID Entity?

Reference: [Hyperledger Indy/Sovrin Comprehensive Architecture Reference Model (INDY ARM) - latest version](https://hyperonomy.com/2019/01/13/hyperledger-indy-sovrin-comprehensive-architecture-reference-model-arm/) - bullets (12) thru (16) in both the diagram, Narration, and principles.

**Comment by rhiaro** [comment]
Lay definition of entity in https://github.com/w3c-ccg/did-spec/commit/776406cf4e4658a622308489775293be1db14556 fixes this
