### ISSUE TITLE
[URIs, URLs, and URNs] Section doesn't conclude with a precise declaration of what a DID is.

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#155]
In https://w3c-ccg.github.io/did-spec/#uris-urls-and-urns, the section doesn't conclude with a precise declaration of what a DID is.

My understanding is that the _id (DID)_ attribute (aka "DID") of a DID Document/DID Entity is actually a URN ...a subclass of URI ...and specifically not a URL.  URL is a centralized concept.   A URL is a locator.

**Comment by jandrieu** [comment]
DIDs are more than the id field on the DID document. They are the URL that resolves to the DID Document.

**Comment by mwherman2000** [comment]
@dmitrizagidulin Separate from #155, this issue is asking for a concluding sentence be added to the end of this section that clearly states that:
"A DID is...."

**Comment by mwherman2000** [comment]
@jandrieu Markus uses some interesting language in this ssimeetup.org video: https://ssimeetup.org/did-resolution-given-did-how-do-retrieve-document-markus-sabadello-webinar-13/:

> DIDs are valid URIs but they are both URNs meaning they are persistent identifiers and they are also URLs because they are dereferencible.
Timecode: https://www.youtube.com/watch?v=gf2g4O3yqCc&t=120

I believe this is the concluding statement that is needed for this section,

**Comment by dmitrizagidulin** [comment]
That seems like reasonable language (that they're both URNs and URLs, with explanation).

**Comment by mwherman2000** [comment]
This discussion has moved to PR https://github.com/w3c-ccg/did-spec/pull/159 (which, in turn, will be closed once @rhiaro has created a new PR for the restructured DID spec).
