### ISSUE TITLE
[Introduction] Is the Purpose of the Draft DID spec clear and correct? Is there a defined Target Audience for the document...

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#157]
Reference: https://w3c-ccg.github.io/did-spec/#purpose-of-this-specification

Draft DID spec issues roll-up: [Decentralized Identifiers (DIDs) v0.11-Issues-mwh1.pdf](https://github.com/w3c-ccg/did-spec/files/2775755/Decentralized.Identifiers.DIDs.v0.11-Issues-mwh1.pdf)

After reviewing each of the current open issues (see the above PDF file), I've realized that the Purpose for the draft DID spec is not clear and potentially, not correct or precise; nor does the document define the Primary Target Audience for the document. ...and I believe the document's content, focus, and precision suffers from the fact that these are not clear/missing.

For example, 

1. Is the primary audience for the draft DID spec software people/builders? e.g. software architects and software developers?  [I think so] ...application developers as well as platform maintainers?

2. Is the purpose of the draft DID spec to explain decentralized identifiers, DID Documents, etc. from the perspective of these being "lower level" technology layer concepts? ...software components/protocols?  [I think so] 

I think this issue needs to be addressed early on (e.g. first) before tackling the other issues listed in the PDF.  

TODO: A specific PR stating a Purpose that is more complete/clear in the eyes of a stated Primary Target Audience is needed.

Cross-references: 

- https://github.com/w3c-ccg/did-spec/issues/121
- https://github.com/w3c-ccg/did-spec/issues/115
- https://github.com/w3c-ccg/did-spec/issues/130

**Comment by mwherman2000** [comment]
The https://w3c-ccg.github.io/did-spec/#purpose-of-this-specification section should be moved up closer to the beginning of the document.

**Comment by jandrieu** [comment]
Closing as I believe the refactor in PR #164 addresses this issue. If not, please raise a new issue in the DIDWG did-spec repo.
