### ISSUE TITLE
Language: At end of day DID+DDO+VRFC becomes "entity profile"

### ISSUE THREAD

**Issue by ChristopherA** [w3c-ccg/did-spec#16]
We need to either describe @manu's term end of day result of an "entity profile" or "persona" and/or come up with a new name for it.

**Comment by msporny** [comment]
This is a terminology debate and I hesitate to bring it up at RWoT6. Will query the group with a strong preference to keep what we have right now (which is "Verifiable Profile") and deal w/ the language in that group as this conversation has little to do w/ the DID Spec. So, suggestion is to close this issue and take it up in the VCWG.

**Comment by msporny** [comment]
The discussion about Entity Profile/Persona is happening in this issue in the VCWG: https://github.com/w3c/vc-data-model/issues/107
