### ISSUE TITLE
All methods must have a name of at least 3 characters

### ISSUE THREAD

**Issue by TomCJones** [w3c-ccg/did-spec#160]
in did-resolution issue 11 I created this request - it was suggested that the issue belonged here as it was a syntax issue. I disagree, I believe it is a governance issue. I am not sure if governance belongs here or in resolution. https://github.com/w3c-ccg/did-resolution/issues/11

please address the issue first about where this belong and only then about the context.

I believe that did method names should reserve ISO 3311 2 character country codes for use by the countries. see https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

in my resolvers I will not resolve 2 character method names that are not sponsored by the relevant country.

**Comment by TomCJones** [comment]
Sorry I was not clear. Yes 2 char names are valid, but are under control of iso std. I suggested it is a governance issue as one possible solution.

**Comment by msporny** [comment]
> Yes 2 char names are valid, but are under control of iso std.

Strong -1 -- the Veres One DID Method is "did:v1" -- we have shipped to customers, built software around that, etc.

I suggest a different did method approach that's under ISO: "did:iso:uk" ... etc.

**Comment by TomCJones** [comment]
since v1 is not in the iso chart (it is only two alpha codes) I might agree to resolve v1. But I would not agree to resolve op, for example.

**Comment by davidlehn** [comment]
@TomCJones Can you explain why country codes, or any other list of codes, should be reserved as method names?

**Comment by TomCJones** [comment]
I could, but no longer see any point in that. Try googling.

**Comment by TomCJones** [comment]
i give up

**Comment by msporny** [comment]
> i give up

Don't give up yet, you're getting community feedback on your proposal. :)

Why is the following not ok?

"did:iso3166:<ANY_ISO3166_CODE>"
