### ISSUE TITLE
[References] What is the current URL for the URL spec we should be referencing?

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#163]
Related to #132, what is the URL for the URL specification we should be referencing in the DID spec?

Reference: https://w3c-ccg.github.io/did-spec/#bib-url

TODO: Update the URL reference in the References
TODO: Replace "[URL]" in the body of the text with a more appropriate/specific identifier.

**Comment by rhiaro** [comment]
RWOT8 proposal:
* [ ] discuss which of the parts of the RFC3986/WHATWG URL definitions are relevant for DIDs? Then we decide which one to reference.
