### ISSUE TITLE
Does the did-spec need to be specific about which parts of the URI RFC it is conformant with?

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#169]
...so we can avoid these types of conversations? https://github.com/w3c-ccg/did-spec/issues/167#issuecomment-462421237

TODO: Add an RFC 3986 specific section to the DID spec called "RFC 3986 Conformance".

**Comment by mwherman2000** [comment]
Talk about how DIDs are conformant ... not if.  There's some subtlies (sp) here: 
1. DIDs can have a specific syntax specification that is structured differently from the URI spec and still be 100% conformant. ... defined as parsable by a URI parser.
2. This is different from DIDs supporting every possible syntax "configuration" in the URI spec. Hope this clear ...it may not be.

I think Dimitri has done a good/great job with the new DID ABNF syntax.

CC: @talltree

**Comment by talltree** [comment]
On Wed, Feb 13, 2019 at 4:11 AM Michael Herman (Toronto) <
notifications@github.com> wrote:

> Talk about how DIDs are conformant ... not if. There's some subtlies (sp)
> here:
>
>    1. DIDs can have a specific syntax specification that is structured
>    differently from the URI spec and still be 100% conformant. ... defined as
>    parsable by a URI parser.
>    2. This is different from DIDs supporting every possible syntax
>    "configuration" in the URI spec. Hope this clear ...it may not be.
>
> I think Dimitri has done a good/great job with the new DID ABNF syntax.
>
> CC: @talltree <https://github.com/talltree>
>
I was at IBM Think all last week so I haven't had a chance to review the
new DID ABNF syntax from Dimitri, but given how out-of-date the old one
was, I'm sure it's an improvement.

I'm going through the past week of CCG email, but in case I don't find it,
can you share a link to Dmitri's new version?

**Comment by brentzundel** [comment]
New abnf: https://github.com/w3c-ccg/did-spec/pull/168

**Comment by talltree** [comment]
Brent, thanks, I had just found it at the same time you sent your email.

I agree with Michael; Dmitri did a good job. (A nit is that I'd shorten
some of the rule names so the lines don't have to wrap, but that's a purely
editorial call that we can discuss in Barcelona.)

**Comment by rhiaro** [comment]
As I understand it a DID URI should be conformant with the whole of RFC 3986. Therefore there is no need to add language about "which parts" (and therefore this issue can be closed). Does anyone disagree with that?

**Comment by talltree** [comment]
Amy, right on, I agree.

**Comment by peacekeeper** [comment]
@mwherman2000 considering the current ABNF grammar in the spec (after merging https://github.com/w3c-ccg/did-spec/pull/189), and considering the discussion in this thread, do you still see an open issue here?
- If yes, could you explain a bit more why and how we need to be more specific about RFC3986 conformance?
- If no, can we close this issue?

**Comment by jandrieu** [comment]
It seems there was consensus on an approach in response to this issue and that an update to the ABNF was merged in based on that consensus.

If there are still outstanding concerns, please raise a new issue in the DIDWG did-spec repo.
