### ISSUE TITLE
Proposal: Define DDO as "DID Descriptor Object" that can bootstrap into EDO "Entity Descriptor Object"

### ISSUE THREAD

**Issue by ChristopherA** [w3c-ccg/did-spec#17]
I would like to propose that DDO is defined as a "DID Descriptor Object" that is the minimum necessary  to bootstrap the into a Linked Data graph model that can fully discover and construct the EDO or "Entity Descriptor Object".

Thus the DID/DDO spec should be about:

a) What at minimum should a DID methods define.

b) What is required to create a DDO that is minimal LD (Linked Data) object that can be bootstrap into a larger EDO.

c) What is require for other parts of the LD graph to prove that they are associated or issued by the DID (what we are currently calling "owner" proofs).

d) What is required for an an updated DDO LD object to prove that it has updated or revoked the old DDO LD object (what we are are currently calling "control" proofs),

e) A pointer(s?) to bootstrap discovery of additional LD objects that are associated with the DID owner proof to establish the constructed EDO (without this pointer the alternative is that the inspector has to discover what they can from info that they know, which is acceptable thus this pointer is optional).

I think it is up to the method spec to define what proofs are required for the issue of claim from this DID. In the BTCR method, the owner proof key is only allowed be a issuer proof key and prove claims if there there are no issue claim proof keys in the EDO graph that are owned by the the DDO.

**Comment by msporny** [comment]
At present, the group seems to have settled on stating that there is no concept of a "bootstrapping DDO". There is either a fully formed DID Document, or there is not, and it is up to the DID Method to define interim pieces that may constitute a non fully formed DID Document. That is, the DID spec specifies what a fully formed DID Document looks like, full stop. We'll have to see if we've answered the rest of Christopher's questions at RWoT6.

**Comment by msporny** [comment]
@talltree to submit a PR for the DID Resolvers section that specifies that intermediate DID Documents SHOULD NOT be returned by Resolvers.

**Comment by talltree** [comment]
I will address this issue when I do my editorial pass after we finish the PRs that @mikelodder7 is submitting.

**Comment by jandrieu** [comment]
Closing this because we moved the issue to the DID Resolution spec. @ChristopherA, please chime in with current thinking about partial DID Documents and let us know if this is still an active item for discussion.
