### ISSUE TITLE
[Validating the DID ABNF] Is there an online validator we can agree to use to objectively validate the DID ABNF against a set of DID URL test/use cases?

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#175]
@talltree @peacekeeper @dmitrizagidulin Is there an online validator we can agree to use to objectively validate the DID ABNF against a set of DID URL test/use cases?

...a web site where we can copy&paste/upload the DID ABNF as well as a list of DID URL test/use cases?

**Comment by talltree** [comment]
@mwherman2000 It's a standard function of ABNF parsers that you can give them an ABNF grammar and then interactively test as many example instances as you want. 7-8 years ago I used an online ABNF parser to do this all the time but I recently looked and couldn't find it any more. But @peacekeeper might know of such a tool (or for that matter build it in an hour or so :-).

**Comment by peacekeeper** [comment]
Right now I've been using this one for quick testing: https://tools.ietf.org/tools/bap/

However, it only allows you to check if an ABNF is valid, it doesn't allow you to run test strings against it.

**Comment by mwherman2000** [comment]
Thank for you for the pointer ...it eventually led me to this: http://bnfparser2.sourceforge.net/index.html

I'll try to check it out today.

**Comment by mwherman2000** [comment]
The ABNF website http://arran.fi.muni.cz/bnfparser2/ was fixed last night.

> From: Vojtech Rehak <xrehak@fi.muni.cz> 
> Sent: March 7, 2019 3:49 AM
> To: Michael Herman (Parallelspace) <mwherman@parallelspace.net>
> Cc: vasek.vacek@gmail.com; petr.gotthard@centrum.cz
> Subject: Re: FW: http://arran.fi.muni.cz/bnfparser2/ is failing with a web server error
> Hi Michael,
> thanks for using our bnfparser2.
> I have just fixed the web portal.
> Feel free to try it.
> Regards,
> Vojtech Rehak
>

**Comment by mwherman2000** [comment]
According to @talltree and @peacekeeper , Appendix A of this document is considered to be the most current working/draft version of the DID ABNF: 

https://github.com/WebOfTrustInfo/rwot8-barcelona/blob/master/draft-documents/understanding-dids-in-greater-depth.md#appendix-a-anbf-for-dids-and-did-urls
