### ISSUE TITLE
[Validating the draft DID] Which version of the ABNF specification should be referenced in the final did-spec?

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#176]
@talltree @peacekeeper Which version of the ABNF specification are we claiming conformance with?

From http://arran.fi.muni.cz/bnfparser2/ ...

> Augmented BNF for Syntax Specifications: ABNF
> ABNF Definition of ABNF
> http://arran.fi.muni.cz/bnfparser2/share/rfc2234-4.abnf
> 
> Augmented BNF for Syntax Specifications: ABNF
> Core Rules
> http://arran.fi.muni.cz/bnfparser2/share/rfc2234-6.1.abnf
> 
> Augmented BNF for Syntax Specifications: ABNF
> ABNF Definition of ABNF
> http://arran.fi.muni.cz/bnfparser2/share/rfc4234-4.abnf
> 
> Augmented BNF for Syntax Specifications: ABNF
> Core Rules
> http://arran.fi.muni.cz/bnfparser2/share/rfc4234-B.1.abnf

**Comment by mwherman2000** [comment]
https://w3c-ccg.github.io/did-spec/#bib-rfc5234

**Comment by peacekeeper** [comment]
> https://w3c-ccg.github.io/did-spec/#bib-rfc5234

@mwherman2000 if I understand correctly, you answered your own question here? Do you think the reference to RFC5234 in the spec is clear enough?

- If yes, would you agree that this issue can be closed?
- If no, do you have a suggestion how to get better clarity on which version of the ABNF specification we are claiming conformance with?

**Comment by jandrieu** [comment]
Closing as this looks addressed in the final draft. Feel free to re-raise over at the DIDWG did-spec repo.
