### ISSUE TITLE
ABNF idchar should include underscore

### ISSUE THREAD

**Issue by victorgrey** [w3c-ccg/did-spec#177]
To accommodate url-safe base64 encoded values, the idchar definition should be
ALPHA / DIGIT / "." / "-" / "_"

**Comment by talltree** [comment]
I agree. I have added it to the DID Matrix Parameters Syntax Proposal at https://docs.google.com/document/d/1TctFY8euBH2wq7Z8c9KccICDZUGZplvhoqlHlFMahGk/edit?usp=sharing
