### ISSUE TITLE
Should DID syntax allow an empty "method-specific-id"?

### ISSUE THREAD

**Issue by peacekeeper** [w3c-ccg/did-spec#198]
There is an open question whether a DID without a `method-specific-id` should be allowed by the ABNF grammar. If yes, then should there be a trailing colon (e.g. `did:example:`) or not (e.g. `did:example`)?

This would make it possible to have a DID and DID Document for a DID method itself.

See https://github.com/w3c-ccg/did-spec/pull/189#discussion_r280993911 and https://github.com/w3c-ccg/did-spec/pull/189#pullrequestreview-231512312 and https://github.com/w3c-ccg/did-spec/pull/187#discussion_r278347044.

**Comment by mwherman2000** [comment]
I'm glad the ABNF was left the way is: allowing for an empty `method-specific-id` ...to enable DID Data (metadata) to be returned about a DID Method (at the method level). For example...

![image](https://user-images.githubusercontent.com/6101736/63255221-7fcff800-c232-11e9-806d-ef1d2e7b6043.png)

**Comment by jandrieu** [comment]
Closing because we've moved it to the DID WG did-spec repo.
