### ISSUE TITLE
Use colon separator or kebab-case for method-specific DID parameter names?

### ISSUE THREAD

**Issue by peacekeeper** [w3c-ccg/did-spec#199]
There is discussion whether method-specific DID parameter names should use colon separators:

`did:foo:21tDAKCERh95uGgKbJNHYp;foo:bar=high`

or kebab-case style:

`did:foo:21tDAKCERh95uGgKbJNHYp;foo-bar=high`

See https://github.com/w3c-ccg/did-spec/pull/189#discussion_r280993986

**Comment by jandrieu** [comment]
Closing because we've moved it to the DID WG did-spec repo.
