### ISSUE TITLE
Details on the use of method-specific DID parameters

### ISSUE THREAD

**Issue by peacekeeper** [w3c-ccg/did-spec#200]
Some details on the rationale and use of method-specific DID parameters need to be clarified, e.g.:

1. What does it mean if a parameter name defined by one method (e.g. `foo`) is used in a DID URL with a different method (e.g. `example`):

`did:example:21tDAKCERh95uGgKbJNHYp;foo:bar=low`

2. Also, discuss whether we want to say anything about hierarchical method namespaces in DID parameter names:

`did:foo:baz:21tDAKCERh95uGgKbJNHYp;foo:baz:hex=b612`

See https://github.com/w3c-ccg/did-spec/pull/189#discussion_r280994030 and https://github.com/w3c-ccg/did-spec/pull/189#discussion_r280994054

**Comment by jandrieu** [comment]
Closing because we've moved it to the DID WG did-spec repo.
