### ISSUE TITLE
Simplify Subtitle, Move Version to End of Title

### ISSUE THREAD

**Issue by ChristopherA** [w3c-ccg/did-spec#203]
This may be silly bikeshedding, but I would suggest that repeating "for Decentralized Identifiers (DIDs)" in the subtitle is redundant as "Decentralized Identifier (DID)" is also in the title line. Short and sweet will mean that the sub-title will likely be included in any mentions of the specification, which I think is a good thing.

If accepted, the full title/subtitle would be:

```
Decentralized Identifier (DID) 0.13 Specification
Data Model and Syntaxes
```

You also may want to consider moving the version to the end of the title and adding a "v".

```
Decentralized Identifier (DID) Specification v0.13
Data Model and Syntaxes
```
-- Christopher Allen

**Comment by peacekeeper** [comment]
@ChristopherA the title is
```
Decentralized Identifiers (DIDs) v0.13
```
not 
```
Decentralized Identifier (DID) 0.13 Specification
```
So I'm not sure how you want to move the version or add a "v" (it's already there).

But I agree shortening the subtitle is a good idea, so I opened a PR for that.
