### ISSUE TITLE
Add "DID controller" to "Terminology" section.

### ISSUE THREAD

**Issue by peacekeeper** [w3c-ccg/did-spec#205]
Also check if "DID controller" should be used in additional places, e.g. see https://github.com/w3c-ccg/did-spec/pull/180/files#r283199888

**Comment by rhiaro** [comment]
DID Controller is now in the terminology section, but leaving this open until we do a sweep to make sure we refer to it appropriately throughout the spec.

**Comment by jandrieu** [comment]
Closing because we've moved it to the DID WG did-spec repo.
