### ISSUE TITLE
[Abstract] Not sure of the intended meaning of the following sentence...

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#211]
> DIDs are URLs that relate a DID subject to means for trustable interactions with that subject. DIDs resolve to DID Documents — simple documents that describe how to use that specific DID. 

Doesn't read well.

**Comment by rhiaro** [comment]
I can't quite pin down what exactly doesn't read well, but how is this rephrasing?

> DIDs are URLs that relate a DID Subject to means for trustable interactions with that subject by way of a DID Document. DID Documents are simple documents that describe how to use that specific DID.

**Comment by jandrieu** [comment]
Closing because we've moved it to the DID WG did-spec repo.
