### ISSUE TITLE
[Abstract] Not sure of the intended meaning of this sentence...

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#212]
> Each DID Document may contain at least three things...

"may" and "at least 3 things" in the same sentence doesn't read well.

**Comment by rhiaro** [comment]
The abstract has been updated with text from the DID WG Charter, which was agreed by the CCG a little while ago after much deliberation. This part now says "Each DID Document may express cryptographic material, verification methods, and/or service endpoints." so I'm closing this issue as the text mentioned is no longer present. If this new abstract is problematic, a new issue for it would be appropriate.
