### ISSUE TITLE
[Absract] "proof purposes" is a new term but is not defined anywhere in the document

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#213]
> Each DID Document may contain at least three things: proof purposes, verification methods, and service endpoints. Proof purposes are combined with verification methods to provide mechanisms for proving things.

**Comment by mwherman2000** [comment]
Ditto for "proof purpose pattern"

**Comment by rhiaro** [comment]
I agree "proof purpose" should be defined properly somewhere. 

I don't see "proof purpose pattern" anywhere in the spec though.

**Comment by jandrieu** [comment]
Closing because we've moved it to the DID WG did-spec repo.
