### ISSUE TITLE
[Abstract] Clarification...

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#215]
> This document specifies a common data model, format, and operations that all DIDs support.

Be more specific: 

> ...all DID methods may support?

or

> ...all DID methods must support?

**Comment by rhiaro** [comment]
We shouldn't put normative sounding language in the abstract. 

These things don't only apply to DID Methods.

Maybe:

> This document specifies a common data model, format, and operations necessary for DIDs, DID Documents and DID Methods.

**Comment by TallTed** [comment]
Similar rewording work was done for, but was apparently never merged into, the same statement in the charter -- https://github.com/w3c-ccg/did-wg-charter/pull/67/files

> This document specifies a common data model, a URL format, and a set of operations that all DIDs support.

**Comment by jandrieu** [comment]
Closing because we've moved it to the DID WG did-spec repo. https://github.com/w3c/did-spec
