### ISSUE TITLE
[Introduction] Clarification...

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#216]
Change

> In a decentralized identity system, entities (in the sense of discrete identifiable units such as—but not limited to—people and organisations) are free to use any shared root of trust.

to

> In a decentralized identity system, entities (in the sense of discrete identifiable units such as—but not limited to—people, organisations, and things (any non-fungible entity)) are free to use any shared root of trust.

...or something similar.

**Comment by jandrieu** [comment]
Closing because we've moved it to the DID WG did-spec repo. https://github.com/w3c/did-spec
