### ISSUE TITLE
[Introduction] Rewording...

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#217]
Change

> Globally distributed ledgers, decentralized P2P networks, or other systems with similar capabilities, provide the means for managing a root of trust with neither centralized authority nor a single point of failure.

to

> Globally distributed ledgers, decentralized P2P networks, or other systems with similar capabilities, provide the means for managing a root of trust without introducing a centralized authority nor a single point of failure.

**Comment by jandrieu** [comment]
Closing as this has been addressed. If concerns remain, please add an issue to the DID WG did-spec repo. https://github.com/w3c/did-spec
