### ISSUE TITLE
[Introduction] Clarify...

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#218]
The following phrase reads well but I have no idea what it is really trying to say....

> to respect the entity’s desired separation of identities, personas, and contexts.

- Personas isn't defined in the documents.

- Is the "contexts" the same "Contexts" defined in section 5.1?

There must be some background context for this phrase that is assumed to be known to the reader but it has not been included in this document.

**Comment by rhiaro** [comment]
I think in this case personas, identities and contexts are the normal English language definitions of the words. I'm not sure how to clarify this further without turning the spec into a dictionary of all not-so-common terms. 

* Perhaps adding something like "...identities, personas and contexts (in the everyday sense of these concepts)"? 
* Maybe we can find a link to a document about the complexities of online identities?
* An example could help? "...identities, personas and contexts (for example keeping separate identifiers for personal and work purposes)."

**Comment by TallTed** [comment]
+1 for the parenthetical example

**Comment by jandrieu** [comment]
Closing because we've moved it to the DID WG did-spec repo. https://github.com/w3c/did-spec
