### ISSUE TITLE
[Introduction] Doesn't read well...

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#220]
> ...writing DID documents on the network for which it is written.

"for which it is written" doesn't read well/make sense.

**Comment by mwherman2000** [comment]
In the new wording, change `on `to `to`:

> The difference is that a DID Method specification, in addition to defining a specific DID scheme, also specifies the methods for resolving and deactivating DIDs and writing DID Documents `on` the appropriate DID Registry.

**Comment by jandrieu** [comment]
Closing because we've moved it to the DID WG did-spec repo. https://github.com/w3c/did-spec
