### ISSUE TITLE
[EXAMPLES] DID examples are needed for the following sections...

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#222]
- https://w3c-ccg.github.io/did-spec/#path
- https://w3c-ccg.github.io/did-spec/#query
- https://w3c-ccg.github.io/did-spec/#fragment

**Comment by aljones15** [comment]
I think I got these right (awaiting review), but added examples in this PR:
https://github.com/w3c-ccg/did-spec/pull/225

**Comment by peacekeeper** [comment]
Fixed by #225. Closing.
