### ISSUE TITLE
DID Test Suite and untestable normative statements

### ISSUE THREAD

**Issue by kimdhamilton** [w3c-ccg/did-spec#228]
Digital Bazaar has developed a DID Test Suite and identified 83 untestable normative statements. Let's discuss on the call for awareness and figure out if there's any tracking or work we need to do in advance of the DID WG.

https://lists.w3.org/Archives/Public/public-credentials/2019Jun/0008.html

**Comment by peacekeeper** [comment]
I imagine https://github.com/w3c-ccg/did-spec/pull/210 partially (but not fully?) addressed this issue?

**Comment by jandrieu** [comment]
Closing because we've moved it to the DID WG did-spec repo. https://github.com/w3c/did-spec
