### ISSUE TITLE
Should "id" be mandatory for "service" and "publicKey"?

### ISSUE THREAD

**Issue by peacekeeper** [w3c-ccg/did-spec#247]
The spec says that each `service` and `publicKey` MUST include an `id` property. The discussions in https://github.com/w3c-ccg/did-spec/issues/238 and https://github.com/w3c-ccg/did-spec/pull/206 and https://github.com/w3c-ccg/did-resolution/issues/37 made me wonder if this should indeed be mandatory.

Not urgent to discuss, but I wanted to keep track of the question.

**Comment by jandrieu** [comment]
Closing because we've moved it to the DID WG did-spec repo. https://github.com/w3c/did-spec
