### ISSUE TITLE
Should/can we drop the owner property on embedded keys?

### ISSUE THREAD

**Issue by cwebber** [w3c-ccg/did-spec#25]
"Embedded" keys have an `owner` property that links back to their parent object in our examples, for example:

``` javascript
{
  "@context": "https;//w3id.org/did/v1",
  "id": "did:example:123456789abcdefghi",
  /* ... */
  "authenticationCredential": [{
    // this key can be used to authenticate as DID ...9938
    "id": "did:example:123456789abcdefghi#keys/1",
    "type": "RsaCryptographicKey",
    "owner": "did:example:123456789abcdefghi",
    "publicKeyPem": "-----BEGIN PUBLIC KEY...END PUBLIC KEY-----\r\n"
  }]
  /* ... */
}
```

This is confusing some readers; why should an object (or rather its embedded object) link back to itself?

In Linked Data Signatures, when we sign/etc things we need to link to a specific key, but we also need to know what the owner of that key is, and for security reasons that requires both the owner and the key link to each other.  For example, of Manu makes a post saying "I like ravioli", the signature needs to link not just to Manu as the one signing it, which of Manu's keys specifically.  So, this makes sense in LDS land generally.

The confusion is, in the example of a DID Document such as above, we don't have a ravioli object pointing to a key pointing to its owner, we have a DID linking to (or appearing to "embed") a key and linking back to *itself*.

The "linking back to itself" is the bit that's causing great amounts of confusion. :)

We could maybe drop the requirement to link back to its owner assuming we're using an "embedded" fragment identifier... but this would be incompatible with Linked Data Signatures, which has good reason to have this for the general case.

**Comment by msporny** [comment]
After a discussion with @rxgrant today about this topic, he seems to be comfortable with leaving owner in there as long as we explain why it exists in some way. 

Resolve this issue by submitting a PR that explains why the owner exists and point to the Linked Data Signatures spec that further elaborates on the need for owner.
