### ISSUE TITLE
Resolutions from RWoT face to face

### ISSUE THREAD

**Issue by cwebber** [w3c-ccg/did-spec#26]
AGREED:

 - fragment being absolute is a SHOULD (or, relative fragments are a SHOULD NOT)
 - authenticationCredential is included in a document *even if* it's generated dynamically eg in bctr
 - credentials should be scoped properties eg `authenticationCredential` instead of `credentials`
 - `owner` is currently used by many LDS types, but it is possible to define a type that would fit in a credentials slot that does not need `owner` if it can justify inference

NOTES:

 - terminology conversations are endless, but what we're calling `permission` object capabilities people call `methods`

**Comment by msporny** [comment]
These agreements are either now in the spec or have been overtaken by events. Closing the issue as I think everything is resolved here.
