### ISSUE TITLE
DID Controller definition needs work

### ISSUE THREAD

**Issue by rhiaro** [w3c-ccg/did-spec#263]
Draft definition as proposed on the 2019-08-08 DID Spec call is

> The entity, or a group of entities, in control of a DID and/or DID Document. Note that the DID Controller may or may not include the DID Subject. 

but this should be less vague and maybe contain some examples of what 'controlling' actually means.

**Comment by jandrieu** [comment]
Closing because we're addressing this in https://github.com/w3c/did-spec/issues/4
