### ISSUE TITLE
Random capitalization of "key terms" ...those that appear in the Terminology section

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#269]
Reference: https://w3c-ccg.github.io/did-spec/#terminology

The Terminology section defines several key terms used throughout the rest of the document.  However, when these key terms appear in the rest of the document, the capitalization is inconsistent ....it appears to be random.  Sample key terms to test with:
DID Document
DID Subject
DID Controller
DID Registry

Action: scan the document for each key term in the Terminology section and, where necessary change the capitalization to conform with that found in the Terminology section.

**Comment by jandrieu** [comment]
Closing because we've moved it to the DID WG did-spec repo. https://github.com/w3c/did-spec
