### ISSUE TITLE
[Convention] Method `0` (zero) become a well-known method for retrieving properties/metadata from/about a particular DID Server

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-spec#271]
[I'm sure this will become contentious]

I propose that Method `0` (zero), aka `did:0`, become a well-known method for retrieving properties/metadata from/about a particular DID Server.  For example...

![image](https://user-images.githubusercontent.com/6101736/63276753-3e0a7600-c261-11e9-9b2c-1441279ae103.png)

**Comment by jandrieu** [comment]
Closing because we've moved it to the DID WG did-spec repo. https://github.com/w3c/did-spec
