### ISSUE TITLE
Add support for ethereumAddress public key type in @context

### ISSUE THREAD

**Issue by awoie** [w3c-ccg/did-spec#274]
The final community specification allows for `ethereumAddress` public key types. We have to add the respective key type to the context to be recognized by 3rd party applications, e.g., uniresolver.io.  

After following the discussion in https://github.com/w3c-ccg/did-spec/pull/270, it seems like we should at least support all public key types that were mentioned in the W3C CCG DID spec. 

PR is pending: see https://github.com/w3c-ccg/did-spec/pull/273

**Comment by brentzundel** [comment]
Work on the DID spec has moved to the DID WG.
If you would like this issue to be addressed, please open it in [the DID WG repo](https://github.com/w3c/did-spec/issues)

**Comment by christianlundkvist** [comment]
@brentzundel, this is not really work on the DID spec, it’s making sure the context file (which is hosted in this repo, see the referenced PR above) matches the DID spec.

**Comment by jandrieu** [comment]
This repo is scheduled to be archived. The CGFR is the last output from the CCG. This should be fixed in the active repo https://github.com/w3c/did-spec/issues

**Comment by awoie** [comment]
I opened the issue in the official WG repo.
