### ISSUE TITLE
copy-paste typo

### ISSUE THREAD

**Issue by wintergao** [w3c-ccg/did-spec#276]
In section 2, Terminology
`DID Query`
`The portion of a DID URL that follows the first question mark character (?). A DID path uses the identical syntax as a URI path. See Section § 4.6 Query .`

Should be:
`The portion of a DID URL that follows the first question mark character (?). A DID query uses the identical syntax as a URI query. See Section § 4.6 Query .`

**Comment by peacekeeper** [comment]
This has been fixed in https://github.com/w3c/did-spec/pull/81.

**Comment by msporny** [comment]
Closing.
