### ISSUE TITLE
Need a way to specify multi-factor key/proof relationships

### ISSUE THREAD

**Issue by csuwildcat** [w3c-ccg/did-spec#29]
I would like to see DID Documents support the notion of keys/proofs being reliant on a combination of keys/proofs to be valid. Some attestations and auth requirements are what I would call 'mission critical', for example:

Say a government adopts decentralized identity systems, and integrates it into their court system. There may be many things that take just one signature from one key linked to the court entity to be authoritative, but some attestations may be so sensitive, with such a severe impact, that the court entity would want to put extra measures in place to up the ante on what it takes to be a valid attestation.

One such case: criminal conviction proofs.

In this case, a court entity may want to exclude any chance that a criminal conviction data object is ever created/signed with just a single key. They may want to specify that a set of three keys are reliant factors that must all sign something for it to be valid.

To do this, we could add a property on key descriptors that allowed the specification of another key in the owning entity's DID Document (or an external key ref, e.g. another DID's keys) that must be included for the key's use to be valid.

Pseudo code:

```json
  {
    "id": "did:example:fooCountyCourt#keys-1",
    "type": "RsaCryptographicKey",
    "owner": "did:example:fooCountyCourt",
    "publicKeyPem": "-----BEGIN PUBLIC KEY...END PUBLIC KEY-----\r\n",
    "factors": [{
         "id": "did:example:fooCountyCourt#keys-2",
         "requirement": "sig"
       },
       {
         "id": "did:example:courtClerkOne#keys-3",
         "requirement": "sig"
       },
       {
         "id": "did:example:courtClerkTwo#keys-1",
         "requirement": "sig"
       }
     ]
  }
```

**Comment by msporny** [comment]
> I would like to see DID Documents support the notion of keys/proofs being reliant on a combination of keys/proofs to be valid.

This is supported at the Linked Data Signature layer via Multi-signature (Set and Chain) support (you need this support on the document being signed):

https://w3c-dvcg.github.io/ld-signatures/#multiple-signatures

This was supported for the authorization field on the DID Document in the RWoT 5 spec, look at Example 9 and search for "minimumSignatures":

https://msporny.github.io/did-spec/#appendix-b-the-generic-did-context-for-json-ld

So that raises the question on whether this should be a part of 'authorization', and not a part of the key descriptions. Ignoring that...

We could probably extend the key descriptions like so to create a new type of MultisignatureKeyChain, riffing off of your example above:

```json
{
  "id": "did:example:fooCountyCourt#keychain-1",
  "type": "MultisignatureKeyChain",
  "owner": "did:example:fooCountyCourt",
  "usage": "signing",
  "publicKey": [
    "did:example:judgeJudy#keys-123",
    "did:example:bailiffRobertson#keys-abc",
    "did:example:defendingAttorney#keys-789",
    "did:example:prosecutingAttorney#keys-xyz"
  ]
}
```

So, that said, there is also an argument that the DID layer may be the wrong layer to put this. Court documents are typically a application layer thing, so the application layer would enforce multiple signatures, not necessarily the DID layer. However, there is nothing to stop some ledger somewhere from implementing the thing above since the DID Document is extensible in this way. I just wouldn't recommend doing it like that.

So, the way to do this would be to not put it in the core DID spec, but create a new key spec that describes how a "MultisignatureKeyChain" would work.

**Comment by jljordan42** [comment]
So, I am probably missing something ... I'm unclear about what the DID is representing in this example. I have in my mind that a DID represents entities like people, orgs, services. This seems be a data object and then seems to suggest that there is some sort of access control to that data object via multiple factors such as 2 or more keys.  Wouldn't a court ruling be a verifiable claim being held by perhaps the court and about a subject and perhaps also held by the subject as well? And the creation of the claim would have the business rules about the authorizations to create the claim in the first place?
I think that is a bit what Manu is suggesting in more technical terms above as I typed this out.

**Comment by msporny** [comment]
> I'm unclear about what the DID is representing in this example.

The DID "did:example:fooCountyCourt" is representing the "Foo County Court". The DID Document (what you get when you look up that DID the blockchain), is listing a cryptographic device (identified by "did:example:fooCountyCourt#keychain-1") that needs 3 key signatures to be considered a valid signature.

> And the creation of the claim would have the business rules about the authorizations to create the claim in the first place?

Yes, the thing creating the Verifiable Credential in the first place would require 3 signatures to even create the finding that someone was guilty. Dan is attempting to encode this logic in the DID Document. The point that I was making was that we may not want to complicate the lower layer with complex business logic and instead push this sort of thing up to the higher levels in the application stack. So, the court software would enforce that 3 signatures thing, not the DID layer. Or to put it another way, any finding that someone was convicted that doesn't also include 3 signatures from the proper parties AND have verifiable claims attached saying that "so and so is an acting court clerk" would not be recognized as a valid conviction.

There are multiple ways to solve this problem... usually the more complex the solution, the further up the stack it should go.

**Comment by jljordan42** [comment]
Thanks Manu for the clarification. I didn't catch on to the fragment part with the #keychain-1 ... my parser must have had a bug!

Yes ... business rules in higher layers for sure.

Maybe this keychain approach is something for setting a special DID if an entity would like to use a multi key scenario for key recovery?

**Comment by csuwildcat** [comment]
The reason it has to go in the DID doc is because there's no chronologically deterministic way to discover the validity of a multi-proof relationship outside of the chain-anchored lineage. This multi-proof relationship must also be backed by the same level of global revocation awareness as underlying keys. I originally spec'd this as being a part of Hubs, but realized it had to at least be possible in the DID doc for the reasons entailed above.

**Comment by msporny** [comment]
Attempting to resolve this issue, which has been hanging out there for a while:

> The reason it has to go in the DID doc is because there's no chronologically deterministic way to discover the validity of a multi-proof relationship outside of the chain-anchored lineage. This multi-proof relationship must also be backed by the same level of global revocation awareness as underlying keys.

Wouldn't the mechanism you would use be to just check the signatures, keys, revocation lists, and signature anchor on the chain (or chains) in question? I agree that you would need all those things in a DID Ledger to prove a signature at a particular point in time but what are you requesting that we add or modify in the DID spec to enable this to happen?

**Comment by talltree** [comment]
@mikelodder7 and I discussed this and we believe that Manu is essentially saying that this issue @csuwildcat raised is not a DID spec issue, but a key description spec issue. If Daniel needs a key description spec that does this kind of multi-sig functionality, that should be a key spec dedicated to that functionality.

**Comment by csuwildcat** [comment]
If a certain type of key description has the fields that allow multiple
keys/proofs to be linked to infer relationships, that's fine. I simply need
a way to have the burden of proof relationship between keys/proofs be
asserted somehow in the DID Doc, because without something (doc props,
descriptor types, etc.) there's no way for the authing/checking party to
know what related elements are required. At first blush, it seems like
Mike's suggestion would work.

**Comment by msporny** [comment]
This is a Linked Data Security thing and should be moved to that WG if/when it's created.

**Comment by jandrieu** [comment]
Should we move this to https://github.com/w3c-dvcg/ld-signatures ?

**Comment by jandrieu** [comment]
@msporny Please comment.

**Comment by msporny** [comment]
> Should we move this to https://github.com/w3c-dvcg/ld-signatures ?

It should probably be ld-proofs... as I can imagine that to do some privileged operation, you might request an M of N proof of work and an M of N signature.

**Comment by msporny** [comment]
Migrated to ld-proofs, closing.
