### ISSUE TITLE
Leverage RFC7518 to specify cryptographic algorithms

### ISSUE THREAD

**Issue by AxelNennker** [w3c-ccg/did-spec#38]
Why not reference [RFC7518](https://www.rfc-editor.org/rfc/rfc7518.txt) to specify cryptographic algorithms?

I think the did-spec should reference [rfc7518](https://www.rfc-editor.org/rfc/rfc7518.txt) whenever cryptographic algorithm names need to be specified.

**Comment by msporny** [comment]
Linked Data Proofs, Linked Data Signatures, and the DID Spec specify "cryptographic suites". For example, these are all cryptographic suites mentioned by the current DID Spec:

Ed25519SignatureAuthentication2018, RsaSignatureAuthentication2018, Ed25519SignatureCapabilityAuthorization2018, etc.

The DID spec doesn't specify things at the RFC7518 level... but the cryptographic suites do, and yes, they should reference RFC7518 when possible.

This issue will be resolved by submitting a PR that adds a section titled "Relationship to JOSE".

**Comment by jandrieu** [comment]
Closing as we have adopted this issue in the new DIDWG repo.
