### ISSUE TITLE
Section 4.3 Authentication Section - rename "authenticationCredential"

### ISSUE THREAD

**Issue by trbouma** [w3c-ccg/did-spec#45]
I propose that "authenticationCredential" be renamed to "authenticatorMechanism" or just "authentication". This is more general and gets away from the term "Credential" which has been overloaded over the years. My preference is "authenticationMechanism".

I note that the EXAMPLE 5 uses "authentication"

**Comment by msporny** [comment]
Fixed. Thank you.

That was old language. The group has settled on "authentication" for now (after a tremendous amount of debate).
