### ISSUE TITLE
The Ed25519 key description needs to be cleared up

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/did-spec#5]
We need a vetted description for the Ed25519 key format. The one in the spec right now is just a first guess at what one might look like. We need an implementer to put a more rigorous example into the spec.

**Comment by msporny** [comment]
Assigning @peacekeeper since he seems to have volunteered on the mailing list to address. Let me know if I misread your email, @peacekeeper.

**Comment by peacekeeper** [comment]
Yes I can try. Should this go into the w3c-dvcg repo (that's where the other signature suites are)? If yes, can you invite me to that org as commiter?

Also +1 to renaming **ld-key-registry** to **ld-cryptosuite-registry**.

**Comment by msporny** [comment]
> invite me to that org as commiter?

Done, invited as an Admin for now. We'll need to fix that orgs permissions to be a bit more nuanced.

> Also +1 to renaming ld-key-registry to ld-cryptosuite-registry.

+1 to that as well.

**Comment by peacekeeper** [comment]
Thx! And you or @dlongley will add the new RsaSignature2018 you mentioned on the mailing list?

**Comment by msporny** [comment]
> Thx! And you or @dlongley will add the new RsaSignature2018 you mentioned on the mailing list?

Yes, it's implemented: https://github.com/digitalbazaar/jsonld-signatures/commit/f583bd4333785b847c6fcddc7065eeb388aa6733

We just need to rev the specs... which is not a super high priority, but we'll get to it in the next few weeks.

**Comment by msporny** [comment]
Renamed ld-key-registry: https://github.com/w3c-ccg/ld-cryptosuite-registry

**Comment by msporny** [comment]
Spec exists now: https://w3c-dvcg.github.io/lds-ed25519-2018/

**Comment by msporny** [comment]
We now have a spec for the key and implementations in Veres One. We may need to refine further, but the original issue has been resolved. Closing the issue.
