### ISSUE TITLE
authentication section typos

### ISSUE THREAD

**Issue by mikelodder7** [w3c-ccg/did-spec#52]
In the authentication section it says 

2. The value of the authentication property should be an array of proof mechanisms.
3. Each proof mechanism must include id, type, and owner properties.

This is not correct, I don't see "id" or "owner 'in any of the examples and I thought the only required field is "type".   Because each proof mechanism MAY be a key description of a valid public key or verification key. A new key description MAY also be defined by a DID method specification.

**Comment by msporny** [comment]
You're correct, this is a spec bug and needs to be fixed. Will cover in my next edit cycle. PRs appreciated.

**Comment by mikelodder7** [comment]
Okay I will try to submit one.

**Comment by peacekeeper** [comment]
This change is already included in the PR https://github.com/w3c-ccg/did-spec/pull/50/ we're discussing right now.

**Comment by msporny** [comment]
> This change is already included in the PR #50 we're discussing right now.

oh right, thanks @peacekeeper. You may want to "Fixes #52" in the PR so this automatically closes when we rebase + merge.
