### ISSUE TITLE
Page not found for DID Method Registry

### ISSUE THREAD

**Issue by xtrycatchx** [w3c-ccg/did-spec#53]
Navigate to [https://w3c-ccg.github.io/did-spec/#specific-did-method-schemes](https://w3c-ccg.github.io/did-spec/#specific-did-method-schemes)

On the second paragraph, click on **DID Method Registry** link. 

Results in Page not found for https://w3c-ccg.github.io/did-spec/did-methods.html

**Comment by talltree** [comment]
It may be that this Registry page has not been set up yet. Manu? Dave?
