### ISSUE TITLE
Explain the reasoning behind using graph data models and JSON-LD

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/did-spec#58]
From @rxgrant at RWoT6:

The spec currently doesn't explain why we're depending on graph-based data models and JSON-LD for extensibility. It also doesn't explain when you can and/or shouldn't process the document as pure JSON. We should add a section explaining this architectural decision. Mention the expectation that developers will parse DID Documents with common libraries (e.g. what happens when "owner" doesn't exist).

**Comment by msporny** [comment]
Resolve this issue by submitting a PR that creates a section on why graph-based data models and JSON-LD were chosen for extensibility, semantic interop, and what happens if we don't have those features.

**Comment by talltree** [comment]
I am in favor of resolving this exactly as Manu describes. I'm willing to
write this or co-write it as we spent a LOT of time working out how DID
documents could strike the right balance between supporting
the JSON-LD graph model for extensibility and the JSON tree model for
simplicity. So I'd really like us to communicate this clearly to developers.
