### ISSUE TITLE
Explain RsaSignature2018 

### ISSUE THREAD

**Issue by AxelNennker** [w3c-ccg/did-spec#60]
Please explain and spec RsaSignature2018. What does it mean that the proofType has this value?

The same for RsaVerificationKey2018, please.

As long as these values appear only in examples and non-normative text they can mean anything.

**Comment by Drabiv** [comment]
Please, also add explanation or point to spec for EcdsaKoblitzSignature2016 (2017, 2018).

**Comment by msporny** [comment]
Horribly out of date specs are here: https://w3c-dvcg.github.io/ld-signatures/ and here: https://w3c-dvcg.github.io/lds-rsa2018/

The proofType stuff is very new (based on the recent consensus in the community around cryptographic suites).

EcdsaKoblitzSignature2016 is an experimental implementation that the Bitcoin/Ethereum devs are playing around with: https://w3c-dvcg.github.io/lds-koblitz2016/

Again, all those specs need to be revved to catch up with where implementations are currently.

**Comment by Drabiv** [comment]
Thanks, for links @msporny. 
It would be really good to have Koblitz 2017 or 2018 suite updated with proof and proofType properties.

**Comment by msporny** [comment]
> It would be really good to have Koblitz 2017 or 2018 suite updated with proof and proofType properties.

"proof" will move into Linked Data Signatures (which Koblitz is built on top of). Same for "proofType", so no update to Koblitz will be necessary and it'll seem as if "proof" and "proofType" existed back in 2016. Yes, this is a strange way to do things, but we don't think it will lead to issues in deployed systems.

**Comment by Drabiv** [comment]
OK. Actually, what I am trying to ask, get clarity on is – "What value should be set into proofType when I sign credential using Ethereum or Bitcoin standard tools (meaning ECDSA secp256k1 signing algorithm; Keccak-256 hashing algorithm?"

**Comment by msporny** [comment]
> What value should be set into proofType when I sign credential using Ethereum or Bitcoin standard tools (meaning ECDSA secp256k1 signing algorithm; Keccak-256 hashing algorithm?

proofType is meant to contain the cryptographic suite that is associated with the key that is doing the signing. If you're in the DID ecosystem, the only valid value for "proofType" at present is "authentication".

For the Veres One DID Method, you can also have "invokeCapability" and "grantCapability", which are currently being renamed to something else.

In the future, I expect "messageEncryption" or "encryption" to also be a valid value for proofType.

**Comment by dlongley** [comment]
Also, the term is "proofPurpose" not "proofType". If we have "proofType" in a spec somewhere it needs to be updated.

**Comment by Drabiv** [comment]
OK, I am confused now. Please see following examples of proofTypes in different specs ("RsaSignature2018", "LinkedDataSignature2015", "EcdsaKoblitzSignature2016"):
[https://w3c.github.io/vc-data-model/#proofs-aka-signatures](https://w3c.github.io/vc-data-model/#proofs-aka-signatures)
[https://w3c-ccg.github.io/did-spec/#proof-optional](https://w3c-ccg.github.io/did-spec/#proof-optional)
[https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust-spring2018/blob/8ac6e0d7e522da2f9e852fc2c04efd2bd67c8141/draft-documents/introducing_btcr.md](https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust-spring2018/blob/8ac6e0d7e522da2f9e852fc2c04efd2bd67c8141/draft-documents/introducing_btcr.md)

If these needs to be changed to "authentication" then please clarify what value should be set for public key type that is used for signing credentials and/or authentication and/or encryption? Also, what should be populated into proofType for keys that are authorization keys in DD and not authentication keys?

**Comment by dlongley** [comment]
@Drabiv,

The confusion is that when you say "proofType" you mean "proof.type", i.e. the "type" property of a proof. That's not what @msporny and I were talking about, we're talking about a literal property called "proofPurpose". As an example:

```js
"proof": {
    "type": "RsaSignature2018",
    "created": "2017-06-18T21:19:10Z",
    "creator": "https://example.com/jdoe/keys/1",
    "proofPurpose": "authentication",
    "nonce": "c0ae1c8e-c7e7-469f-b252-86e6a0e7387e",
    "jws": "BavEll0...W3JT24"
  }
```

The "proof.type" is "RsaSignature2018". The "proofPurpose" is "authentication". This means that the type of proof is an RSA signature according to the "RsaSignature2018" signature suite -- and its *purpose* (why the author created the signature) is for authentication.

**Comment by dlongley** [comment]
To further elaborate, a signature author would specify different keys for different purposes in their DID document:

```js
{
  "id": "did:method1:1234",
  "authentication": [{
    "type": "RsaSignatureAuthentication2018",
    "publicKey": [{
      "id": "did:method1:1234#auth-key-1",
      "type": "RsaVerificationKey2018",
      "owner": "did:method1:1234",
      "publicKeyPem": "..."
    }, ...]
  }, ...],
  "invokeCapability": [{
    "type": "RsaSignatureAuthentication2018",
    "publicKey": [{
      "id": "did:method1:1234#ocap-key-1",
      "type": "RsaVerificationKey2018",
      "owner": "did:method1:1234",
      "publicKeyPem": "..."
    }, ...]
  }, ...]
}
```

And then signature validators would take the signature that an author created, find its key and its purpose, and ensure the key owner's DID Document lists the key underneath the purpose.

**Comment by Drabiv** [comment]
All right, got it. Thanks @dlongley! I guess, I confused apples with oranges. Sorry, about that.
But while on this topic, now if I understood correctly - when I use Bitcoin/Ethereum algos for signing, I should set "proof.type" value to "EcdsaKoblitzSignature2016" .
So back to my question original request:
> It would be really good to have Koblitz 2017 or 2018 suite updated with proof and proofType properties.

What I meant is to have Koblitz siging specs ([https://w3c-dvcg.github.io/lds-koblitz2016/](https://w3c-dvcg.github.io/lds-koblitz2016/)) updated to allow "proof" and "proof.type" propertiesso that they are compliant with VC spec ([https://w3c.github.io/vc-data-model/#proofs-aka-signatures](https://w3c.github.io/vc-data-model/#proofs-aka-signatures))

**Comment by dlongley** [comment]
@Drabiv,

Yes, it would be nice to get the koblitz signature suite updated -- see related:

https://lists.w3.org/Archives/Public/public-credentials/2018Mar/0008.html

**Comment by Drabiv** [comment]
Thanks @dlongley.  I've checked [https://w3id.org/security/v2](https://w3id.org/security/v2) and it does not have description of EcdsaKoblitzSignature2016, so I guess it will be not correct to use it as context for "proof.type" = "EcdsaKoblitzSignature2016"
I'd make PR to change spec myself, but I am too inexperienced with these specs for now, to try doing it.

**Comment by AxelNennker** [comment]
How about not specifying signature schemes in did-spec at all but referring to a registry of currently known signatures  and leaving the details to the implementations?

Like OAuth2 is an authentication framework and does not define the format of access tokens.
(Although there is a close relationship between OAuth2 AZ and resource server...)

This approach is maybe not the best for interoperability...

Or refer to the registry in all places where a signature is needed.

**Comment by msporny** [comment]
> How about not specifying signature schemes in did-spec at all but referring to a registry of currently known signatures and leaving the details to the implementations?

Yes, this is exactly what the current plan is... just haven't had the spare cycles to update the specs to align with the plan.

**Comment by dlongley** [comment]
@Drabiv,

https://w3id.org/security/v2 pulls in https://w3id.org/security/v1 ... so it will include `EcdsaKoblitzSignature2016`.

**Comment by kimdhamilton** [comment]
Question: does this issue belong in the DID spec, or should it be moved to a CCG repo?

I think the only action item for the DID spec itself is ensuring the samples are up to date (if not already)

**Comment by AxelNennker** [comment]
Somebody willing to add all these algs to [JWA](https://tools.ietf.org/html/rfc7518) ?

**Comment by jandrieu** [comment]
Closing as we have adopted this issue in the new DIDWG repo.

**Comment by AxelNennker** [comment]
> Closing as we have adopted this issue in the new DIDWG repo.

A link to the new issue would be nice here

**Comment by msporny** [comment]
@AxelNennker now included (see above).
