### ISSUE TITLE
Is the `guardian` field duplicating functionality provided by the `control` field?

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/did-spec#8]
Does the `guardian` field duplicate functionality provided by the `control` field?

**Comment by ChristopherA** [comment]
I'm quite uncomfortable with guardian being in the the DID 1.0 spec. It either belongs in a future spec (in which it is probably some form of owner and control proof with a tag="guardian" but is otherwise the same as other proofs, or should be part of the Sovrin method spec.

**Comment by msporny** [comment]
The group has determined that authorization is out of scope for now and has a more narrow definition for the `authentication` field. Work continues on object capabilities for performing guardianship and delegation as well as other delegation mechanisms envisioned by the Evernym team. CLosing the issue as there isn't anything left to do here for DID 1.0.
