### ISSUE TITLE
What happens when you feed a did: URL to a URL resolver?

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/did-spec#80]
@gklyne wrote:
> 2. Hierarchical URI scheme?  Is the scheme intended to operate in  a  hierarchical fashion?  RFC 3986 defines a (hierarchical) reference resolution procedure that operates on any URI containing "/"  characters (which are part of your "did-path" syntax. Conventionally, this works in conjunction with an "authority" component that is introduced by "//", but your scheme proposal does not use "authority" syntax.  I'm not sure if there are any potential surprises in store if resolution is attempted with DID URIs.

**Comment by msporny** [comment]
Run experiments where we feed various DID URLs (basic, basic+service, basic+service+path, basic+path+fragment, etc.) to a URL resolver library and see what happens.

**Comment by peacekeeper** [comment]
I believe most URI parsers would be able to correctly extract query and fragment, but wouldn't be able to interpret the rest of the DID syntax (method, method-specific identifier, service, path). Of course specialized DID URI parsers could do that.

**Comment by gklyne** [comment]
My comment wasn't so much to do with _parsing_ a `did:` URI - I agree most parsers should handle that OK.  

I was more concerned with what surprises might be in store if relative URI references were used in connection with a `did:` base URI (cf. https://tools.ietf.org/html/rfc3986#section-5)

**Comment by peacekeeper** [comment]
Quick note that this issue is relevant to the [Service Endpoint Construction](https://w3c-ccg.github.io/did-resolution/#service-endpoint-construction) algorithm in the DID Resolution spec. Perhaps we should create a new issue over there and close this one.

**Comment by jandrieu** [comment]
Closing as we have adopted this issue in the new DIDWG repo.
