### ISSUE TITLE
Update relationship between DID spec and URI spec

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/did-spec#81]
@gklyne wrote:
> (nit) You say "Conceptually, the relationship of this specification and a DID method specification is similar to the relationship of the IETF generic URI specification ([[RFC3986]]) and a specific URI scheme" - to me, it feels more like the relationship between the URN specification and a specific URN namespace ID.

**Comment by msporny** [comment]
Create a PR to update the spec language to make relationship between DID spec and URI spec more accurate.

**Comment by ppKrauss** [comment]
Hi @msporny, yes DID-spec resembles URN...

... perhaps the first step is to show "how to do this in the descentralized way": the new [RFC 8141](https://tools.ietf.org/html/rfc8141) was good, but not changed the central role of [IANA in the control of urn-namespaces](http://www.iana.org/assignments/urn-namespaces/urn-namespaces.xhtml)... Of course, with URN space registered, you can go ahead using concepts as *resolution*, a central mechanism for URNs,  that can be descentralized.

URNs also offers a  wide list of good use cases, to adapt here. The main use cases are pehaps the most complex ones, with hierarchical uniform names: as DNS, more centralization in the root-authorities. Document idenfiers, as [DOI](https://en.wikipedia.org/wiki/Digital_object_identifier), [ELI](https://en.wikipedia.org/wiki/European_Legislation_Identifier) or [URN LEX](https://en.wikipedia.org/wiki/Lex_(URN)), all are conceptually URNs, all good use cases. The URN LEX shows  the broader "path of decentralization".

**Comment by peacekeeper** [comment]
Fixed by https://github.com/w3c-ccg/did-spec/pull/180. That PR added a NOTE which mentions both 1. the relationship between the "generic URI specification" and a "specific URI scheme", and 2. the relationship between the "generic URN specification" and a "specific URN namespace definition". Closing.
