### ISSUE TITLE
Fragment identifier semantics are independent of URI scheme

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/did-spec#82]
@gklyne wrote:
> 3. DID fragments - the URI specification reserves the interpretation  of fragment ids to the MIME type of a representation of the  identified resource, and: "Fragment identifier semantics are  independent of the URI scheme and thus cannot be redefined by scheme  specifications." -- https://tools.ietf.org/html/rfc3986#section-3.5 I would suggest the fragment id interpretation maybe could be  associated with a MIME type defined for the DID document?

**Comment by msporny** [comment]
Create a PR that adds a MIME Type registration section to the specification.

**Comment by peacekeeper** [comment]
Do we need a new MIME type or use the existing `application/ld+json` ?

**Comment by msporny** [comment]
@peacekeeper wrote:
> Do we need a new MIME type or use the existing application/ld+json ?

I expect we need a MIME subtype... application/did+ld+json (or something like that). If you don't do that, you have to come up with heuristics wrt. figuring out if you're actually dealing w/ a DID Document. The latter can be done, but it's not the recommended path for Web architecture.

**Comment by TomCJones** [comment]
What is the status of minetype

**Comment by msporny** [comment]
This issue has been transferred for processing by the DID WG.
