### ISSUE TITLE
DID Method discovery mechanism requirement

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/did-spec#83]
@gklyne wrote:
> maybe every DID service should have an associated DID  document, which among other things connects the method name to its service access point(s), complete with cryptographic verification content.  This document could in turn be served by any and/or all DID services.  In this respect, the various DID services might function  like multiple DNS root servers, and starting from any one of them,  the others are discoverable.  This is not a thought-out proposal, and is probably shot through with holes, but I offer it for consideration (or not!).

**Comment by gklyne** [comment]
Ack.  It was just a thought :)

Close?

**Comment by gklyne** [comment]
Ack.  It was just a thought :)

Close?

**Comment by msporny** [comment]
> Close?

Let's let this hang out there for a few weeks to get other feedback before closing. It is possible that I missed something.

**Comment by peacekeeper** [comment]
Related to https://github.com/w3c-ccg/did-resolution/issues/26 and https://github.com/w3c-ccg/did-spec/issues/198.

**Comment by jandrieu** [comment]
Closing as we have adopted this issue in the new DIDWG repo.
