### ISSUE TITLE
The DID spec is missing a link to DID Method registry location

### ISSUE THREAD

**Issue by Fak3** [w3c-ccg/did-spec#87]
In the end of the section 1.1.4 there is a hint: "For a list of DID Methods and their corresponding specifications, see Appendix". But there is no appendix in this spec. And the spec does not have any link to a place where one can learn about existing DID Methods.

**Comment by Fak3** [comment]
Ah, just found that the spec does not explicitly name the Appendix, but has sections `A. Registries` and `B. Real world examples`. So the section 1.1.4 can have a link to section A, and\or those sections could somehow indicate their appendix role.

**Comment by msporny** [comment]
Thanks @Fak3, fixed in f6ebf04ae649a28934e747754c6495cf61004dcf.
