### ISSUE TITLE
how about to invite Wikidata? 

### ISSUE THREAD

**Issue by ppKrauss** [w3c-ccg/did-spec#92]
Hi, can I suggest something?

To invite Wikidata (or Wikimedia Foundation), perhaps as part in the board of this spec. There are Digital Bazaar, 3 Round Stones, OpenLink Software, ... But no ORG specialized in IDs.

The main example of free and **general interest IDs** are the Wikidata IDs, such as [Q5](http://wikidata.org/entity/Q5) for the *Person* concept or  [Q14748](http://wikidata.org/entity/Q14748) for the usual *Table* concept. Wikidata is in close cooperation with DBpedia, and work with OpenstreetMap, SchemaOrg and other organizations, that must to control IDs, and are in reciprocal adoption of the Wikidata ID. 

Exampe: Berlin, the Wikidata concept [Q64](http://wikidata.org/entity/Q64), is redirect (by [OSM relation ID](https://www.wikidata.org/wiki/Property:P402)) to its polygonal representation as [relation 62422](https://www.openstreetmap.org/relation/62422) (and reciprocally OSM use [`key:wikidata`](https://wiki.openstreetmap.org/wiki/Key:wikidata)), by [european's Nomenclature of Territorial Units](http://dd.eionet.europa.eu/) to the [DE3  territorial division](http://dd.eionet.europa.eu/vocabularyconcept/common/nuts/DE3), etc.  So Wikidata ID is the "sovereign ID" for some practical uses, as in OSM maps.

-----

I believe that the Wikidata community can benefit from this discussion at W3c-ccg/DID-spec, and perhaps help to implement good use cases, etc. And inverse: this  discussion will convince people in the Wikidata Community to better practices, as the managed of the JSON DID Document, etc.

**Comment by Dmole** [comment]
Should also RFC Tor and Mozilla.

**Comment by rhiaro** [comment]
Closing, as this isn't spec-related, but if you'd like to pick this back up perhaps you could open an issue in https://github.com/w3c-ccg/community
