### ISSUE TITLE
Standardize the key revocation list

### ISSUE THREAD

**Issue by satazor** [w3c-ccg/did-spec#96]
Currently the specs state:

> If a public key does not exist in the DID Document, it MUST be assumed the key has been revoked or is invalid. The DID Document MAY contain revoked keys. A DID Document that contains a revoked key MUST also contain or refer to the revocation information for the key (e.g. a revocation list). Each DID Method specification is expected to detail how revocation is performed and tracked.

This means that is up to each DID method spec to specify how to obtain the revoked keys list. The issue is that the data structure for this list is not enforced, reducing the interoperability of the data model for that list.

In my view, it's important to standardize the data model of the revocation list. The reason is that there are many use-cases where we might want to verify signatures of arbitrary data that was signed by identities. To do just that that we must:

- Verify the signature against a public key
- Check if the same public key is or was listed in DID document; in case it's in the revocation list, check if the timestamp of when the key was revoked is higher than the timestamp of the signature of the data.

It will become a mess for app developers if we don't have a standardized and well defined revocation list. More specifically, app developers we would need to create "adapters" to build a canonical data model of the revocation list.

Thanks.

**Comment by peacekeeper** [comment]
I think we will have several situations like this, where features of the DID document should be standardized but remain optional (because not all DID methods may support this). Besides key revocation, another example is versioning.

**Comment by peacekeeper** [comment]
Related to https://github.com/w3c-ccg/did-spec/issues/166 and https://github.com/w3c-ccg/did-resolution/issues/37

**Comment by jandrieu** [comment]
Closing as we have adopted this issue in the new DIDWG repo.
